#!/bin/sh
#
# Perform necessary datadog-agent removal steps after package is uninstalled.
#
# .deb: STEP 3 of 5
# .rpm: STEP 5 of 6
# .bff: STEP ? of ? (TODO)

INSTALL_DIR=/opt/datadog-agent
LOG_DIR=/var/log/datadog
CONFIG_DIR=/etc/datadog-agent

# Remove the symlink to the binary.
rm -f "/usr/bin/datadog-agent"

# TODO: possible remove the user and group (debian purge in postinst (?))  
# NOTE: it's not clear we want to do this, so let's figure it out ^^  

# echo "Deleting dd-agent user"
# deluser dd-agent --quiet
# echo "Deleting dd-agent group"
# getent group dd-agent >/dev/null && delgroup dd-agent --quiet || true
echo "Force-deleting $INSTALL_DIR"
rm -rf $INSTALL_DIR
rm -rf $LOG_DIR
rm -rf $CONFIG_DIR

exit 0
