#!/bin/sh
#
# Perform necessary datadog-agent setup steps after package is installed.
# NOTE: for .rpm, see posttrans instead
#
# .deb: STEP 2 of 5
# .rpm: STEP 3 of 6
# .bff: STEP ? of ? (TODO)

INSTALL_DIR=/opt/datadog-agent
LOG_DIR=/var/log/datadog
CONFIG_DIR=/etc/datadog-agent
SERVICE_NAME=datadog-agent


# TODO: on debian the user is created here, in rhel in the preinst
#       figure out which one makes sense on AIX - not even sure this
#       script applies, the other one definitely does.


# TODO: Set proper rights to the dd-agent user
# chown -R dd-agent:dd-agent ${CONFIG_DIR}
# chown -R dd-agent:dd-agent ${LOG_DIR}
# chown -R dd-agent:dd-agent ${INSTALL_DIR}

# TODO: Enable and restart the agent service here on Debian platforms
# On RHEL, this is done in the posttrans script

if [ ! -f "$CONFIG_DIR/datadog.yaml" ]; then
    # No datadog.yaml file is present. This is probably a clean install made with the
    # step-by-step instructions/an automation tool, and the config file will be added next.
    echo "No datadog.yaml file detected, not starting the agent"
else
    echo "TODO: restart the agent service"
fi

exit 0
