#!/bin/sh
#
# Perform necessary datadog-agent setup steps prior to remove the old package.
#
# .deb: STEP 1 of 5
# .rpm: STEP 4 of 6
# .bff: STEP ? of ? (TODO)

INSTALL_DIR=/opt/datadog-agent
SERVICE_NAME=datadog-agent


# TODO: fix this because there's no systemd or upstart on AIX
#       just keeping the functions around for reference.
stop_agent()
{
    # Stop an already running agent
    if command -v systemctl >/dev/null 2>&1; then
        systemctl stop $SERVICE_NAME || true
    elif command -v initctl >/dev/null 2>&1; then
        initctl stop $SERVICE_NAME || true
    else
        echo "[ WARNING ]\tCannot detect a supported init system. The datadog-agent package only provides service files for systemd and upstart."
    fi
}

# TODO: fix this because there's no systemd or upstart on AIX
#       just keeping the functions around for reference.
deregister_agent()
{
    # Disable agent start on system boot
    # Only supports systemd and upstart
    if command -v systemctl >/dev/null 2>&1; then
        # Force systemd to ignore the sysvinit scripts. Only cosmetic, remove some irrelevant warnings during upgrade
        SYSTEMCTL_SKIP_SYSV=true systemctl disable $SERVICE_NAME || true
    elif command -v initctl >/dev/null 2>&1; then
        # Nothing to do, this is defined directly in the upstart job file
        :
    else
        echo "[ WARNING ]\tCannot detect a supported init system. The datadog-agent package only provides service files for systemd and upstart."
    fi
}

remove_py_compiled_files()
{
    # Delete all the .pyc files in the embedded dir that are part of the agent's package
    if [ -f "$INSTALL_DIR/embedded/.py_compiled_files.txt" ]; then
        # (commented lines are filtered out)
        cat $INSTALL_DIR/embedded/.py_compiled_files.txt | grep -v '^#' | xargs rm -f
    fi
}

# TODO: make sure this all makes sense on AIX. 
#       Already removed the debian relevant portion keeping
#       the RPM bits (just because RPMs are supported on AIX).
#      
#       FIGURE OUT WHAT MAKES SENSE ON AIX HERE.

## stop_agent
## deregister_agent
## 
## case "$*" in
##     0)
##         # We're uninstalling.
##         remove_py_compiled_files
##     ;;
##     1)
##         # We're upgrading.
##         # The preinst script has taken care of removing the .pyc/.pyo files
##     ;;
##     *)
##     ;;
## esac

# Delete all .pyc files in the `agent/` and the `bin/agent/dist` dirs
# find $INSTALL_DIR/agent -name '*.py[co]' -type f -delete || echo "Unable to delete .pyc files in $INSTALL_DIR/agent"

exit 0
