#!/bin/sh
#
# Perform necessary datadog-agent setup steps after package is installed.
# NOTE: for .rpm, see posttrans instead
#
# .deb: STEP 2 of 5
# .rpm: STEP 3 of 6
# .bff: STEP ? of ? (TODO)

set -e

INSTALL_DIR=/opt/datadog-agent
LOG_DIR=/var/log/datadog
CONFIG_DIR=/etc/datadog-agent
SERVICE_NAME=datadog-agent
DATADOG_USER=dd-agent
DATADOG_GROUP=dd-agent

create_datadog_user_aix()
{
    # add /usr/bin/false to the list of allowed shells
    # NOTE: this is all terrible and makes kittens cry.
    # it should all be replaced by a single, idempotent command
    set +e
    /usr/bin/lssec -f /etc/security/login.cfg -s usw -a shells | /usr/bin/grep "/usr/bin/false" > /dev/null
    RC=$?
    set -e
    if [ "${RC}" != "0" ]; then
	  SHVAL=`/usr/bin/lssec -f /etc/security/login.cfg -s usw -a shells | /usr/bin/cut -d '=' -f2`
	  /usr/bin/chsec -f /etc/security/login.cfg -s usw -a shells="${SHVAL},/usr/bin/false"
    fi

    # create the system user
    mkuser pgrp="${DATADOG_GROUP}" shell="/usr/bin/false" home="${INSTALL_DIR}" ${DATADOG_USER}
}

create_datadog_user_group()
{
    # create datadog group
    set +e
    grep "^${DATADOG_GROUP}:" /etc/group > /dev/null
    RC=$?
    set -e
    if [ "${RC}" != "0" ]; then
	  mkgroup ${DATADOG_GROUP}
    fi

    # create datadog user
    set +e
    grep "^${DATADOG_USER}:" /etc/passwd > /dev/null
    RC=$?
    set -e
    if [ "${RC}" != "0" ]; then
	  create_datadog_user_aix
    fi
}

create_system_services()
{
    set +e
    lssrc -s ${SERVICE_NAME} > /dev/null
    RC=$?
    set -e
    if [ "${RC}" != "0" ]; then
        mkssys -s ${SERVICE_NAME} -p "${INSTALL_DIR}/agent/agent.py" -a "-m start" -u ${DATADOG_USER} -S -n 15 -f 9 > /dev/null
    fi

    # adding inittab entry if non-existant
    set +e
    lsitab ${SERVICE_NAME} > /dev/null
    RC=$?
    set -e
    if [ "${RC}" != "0" ]; then
        mkitab "${SERVICE_NAME}:2:respawn:/usr/bin/startsrc -s ${SERVICE_NAME}"
    fi
}

create_datadog_user_group
create_system_services

exit 0
