#! /bin/sh
#
# This script is RPM-specific
# It is run at the very end of an install/upgrade of the package
# It is NOT run on removal of the package
#
# .deb: n/a
# .rpm: STEP 6 of 6
# .bff: STEP ? of ? (TODO)

INSTALL_DIR=/opt/datadog-agent
CONFIG_DIR=/etc/datadog-agent
SERVICE_NAME=datadog-agent

# TODO: Not sure if this should run on AIX (possibly if using RPMs)
#       but probably not with BFFs. Steps detailed below...

# TODO: enable the service with the init system

if [ ! -f "$CONFIG_DIR/datadog.yaml" ]; then
    # No datadog.yaml file is present. This is probably a clean install made with the
    # step-by-step instructions/an automation tool, and the config file will be added next.
    echo "No datadog.yaml file detected, not starting the agent"
else
    echo "TODO: restart the agent service"
fi

exit 0
