#!/bin/sh
#
# Perform necessary datadog-agent setup steps after package is installed.
# NOTE: for .rpm, see posttrans instead
#
# .deb: STEP 2 of 5
# .rpm: STEP 3 of 6
# .bff: STEP ? of ? (TODO)

set -e

INSTALL_DIR=/opt/datadog-agent
LOG_DIR=/var/log/datadog
CONFIG_DIR=/etc/datadog-agent
SERVICE_NAME=datadog-agent
DATADOG_USER=dd-agent
DATADOG_GROUP=dd-agent

create_datadog_user_aix()
{
    # add /usr/bin/false to the list of allowed shells
    # NOTE: this is all terrible and makes kittens cry.
    # it should all be replaced by a single, idempotent command
    set +e
    /usr/bin/lssec -f /etc/security/login.cfg -s usw -a shells | /usr/bin/grep "/usr/bin/false" > /dev/null
    RC=$?
    set -e
    if [ "${RC}" != "0" ]; then
	  SHVAL=`/usr/bin/lssec -f /etc/security/login.cfg -s usw -a shells | /usr/bin/cut -d '=' -f2`
	  /usr/bin/chsec -f /etc/security/login.cfg -s usw -a shells="${SHVAL},/usr/bin/false"
    fi

    # create the system user
    mkuser pgrp="${DATADOG_GROUP}" shell="/usr/bin/false" home="/opt/datadog-agent" ${DATADOG_USER} 
}

create_datadog_user_group()
{
    # create datadog group
    set +e
    grep "^${DATADOG_GROUP}:" /etc/group > /dev/null
    RC=$?
    set -e
    if [ "${RC}" != "0" ]; then
	  mkgroup ${DATADOG_GROUP} 
    fi

    # create sensu user
    set +e
    grep "^${DATADOG_USER}:" /etc/passwd > /dev/null
    RC=$?
    set -e
    if [ "${RC}" != "0" ]; then
	  create_datadog_user_aix
    fi
}

create_system_services()
{
    set +e
    rmssys -s ${SERVICE_NAME} 2>&1 > /dev/null
    set -e
    mkssys -s ${SERVICE_NAME} -p "/opt/datadog-agent/agent/agent.py" -a "-b start" -u ${DATADOG_USER} -S -n 15 -f 9 > /dev/null

    # adding inittab entry
    mkitab "${SERVICE_NAME}:2:respawn:/usr/bin/startsrc -s ${SERVICE_NAME}"
}

# TODO: on debian the user is created here, in rhel in the preinst
#       figure out which one makes sense on AIX - not even sure this
#       script applies, the other one definitely does.


# TODO: Set proper rights to the dd-agent user
chown_datadog_dirs()
{
  chown -R ${DATADOG_USER}:${DATADOG_GROUP} ${CONFIG_DIR}
  chown -R ${DATADOG_USER}:${DATADOG_GROUP} ${LOG_DIR}
  chown -R ${DATADOG_USER}:${DATADOG_GROUP} ${INSTALL_DIR}
}

create_datadog_user_group
chown_datadog_dirs
create_system_services

## TODO: Enable and restart the agent service here on Debian platforms
## On RHEL, this is done in the posttrans script
# if [ ! -f "$CONFIG_DIR/datadog.yaml" ]; then
#   # No datadog.yaml file is present. This is probably a clean install made with the
#   # step-by-step instructions/an automation tool, and the config file will be added next.
#   echo "No datadog.yaml file detected, not starting the agent"
# else
#   echo "TODO: restart the agent service"
# fi

exit 0
