#!/bin/sh
#
# Perform necessary datadog-agent setup steps before package is installed.
#
# .deb: STEP 2 of 5
# .rpm: STEP 2 of 6
# .bff: STEP ? of ? (TODO)

INSTALL_DIR=/opt/datadog-agent
LOG_DIR=/var/log/datadog
SERVICE_NAME=datadog-agent

set -e

tentative_stop_datadog_services()
{
  # Stop an already running agent if it exists
  set +e
  stopsrc -s ${SERVICE_NAME} > /dev/null 2>&1 || true
  sleep 6
  set -e
}

tentative_stop_datadog_services

# Delete all the .pyc/.pyo files in the embedded dir that are part of the old agent's package
if [ -f "$INSTALL_DIR/embedded/.py_compiled_files.txt" ]; then
    # (commented lines are filtered out)
    cat $INSTALL_DIR/embedded/.py_compiled_files.txt | grep -v '^#' | xargs rm -f
fi

exit 0
