#!/bin/sh
#
# Perform necessary datadog-agent setup steps prior to remove the old package.
#
# .deb: STEP 1 of 5
# .rpm: STEP 4 of 6
# .bff: STEP ? of ? (TODO)

INSTALL_DIR=/opt/datadog-agent
SERVICE_NAME=datadog-agent
PYC_COMPILED_FILES=$INSTALL_DIR/embedded/.pyc_compiled_files.txt


stop_datadog_services()
{
  # Stop an already running agent
  set -e
  stopsrc -s ${SERVICE_NAME} > /dev/null 2>&1 || true
}

# TODO: make sure this all makes sense on AIX.
#
#       Enable once we pre-compile the bytecode.
remove_py_compiled_files()
{
    # Delete all the .pyc files in the embedded dir that are part of the agent's package
    if [ -f "$PYC_COMPILED_FILES" ]; then
        # (commented lines are filtered out)
        cat $PYC_COMPILED_FILES | grep -v '^#' | xargs rm -f
    fi
}


# Delete all .pyc files in the `agent/` and the `bin/agent/dist` dirs
remove_py_compiled_files

stop_datadog_services

# wait for services to stop
sleep 6

exit 0
